Metatavu/vp-kuljetus-transport-management-specs

.github/workflows/check-generated-specs.yaml, services/vehicle-management-services.yaml, tools/create-specs/src/index.ts, tools/create-specs/src/types.ts, tyk/vehicle-management-services.json, tyk/work-planning-services.json
=> Feature 1 automated checks for generated specs

services/vehicle-management-services.yaml, specs/app.yaml, specs/full.yaml, specs/management.yaml, tyk/vehicle-management-services-oas.json, tyk/vehicle-management-services.json
=> Added support for trailers

services/vehicle-management-services.yaml, specs/app.yaml, specs/full.yaml, specs/management.yaml, tyk/vehicle-management-services-oas.json, tyk/vehicle-management-services.json, tyk/work-planning-services.json
=> Feature 5 vehicles

.github/workflows/check-generated-specs.yaml, services/vehicle-management-services.yaml, specs/app.yaml, specs/full.yaml, specs/management.yaml, specs/vehicle-data-receiver.yaml, tools/create-specs/src/consts.ts, tools/create-specs/src/index.ts, tools/create-specs/src/types.ts, tyk/vehicle-management-services-oas.json, tyk/vehicle-management-services.json, tyk/work-planning-services.json
- added telematic data endpoint
- removed redundant tags from specs
- fixed full spec tag names
- docker container dependency is now pulled to it's place when the script runs
Resolves #7
=> Feature 7 telematic data

services/vehicle-management-services.yaml, specs/app.yaml, specs/full.yaml, specs/management.yaml, specs/vehicle-data-receiver.yaml, tyk/vehicle-management-services-oas.json, tyk/vehicle-management-services.json
- renamed trailer to towable
- removed towableIds maxLength from vehicle
- added type to truck and towable
Resolves #9
=> Truck and trailer changes

services/delivery-info-services.yaml, specs/app.yaml, specs/full.yaml, specs/management.yaml, tools/create-specs/src/consts.ts, tyk/delivery-info-services-oas.json, tyk/delivery-info-services.json
=> Added customer sites specs

services/delivery-info-services.yaml, specs/app.yaml, specs/full.yaml, specs/management.yaml, tools/create-specs/src/consts.ts, tyk/delivery-info-services-oas.json, tyk/delivery-info-services.json
=> Added freight specs

services/delivery-info-services.yaml, specs/app.yaml, specs/full.yaml, specs/management.yaml, tools/create-specs/src/consts.ts, tyk/delivery-info-services-oas.json, tyk/delivery-info-services.json
=> Added freight unit

services/delivery-info-services.yaml, services/user-management-services.yaml, services/vehicle-management-services.yaml, services/work-planning-services.yaml, specs/app.yaml, specs/full.yaml, specs/management.yaml, specs/vehicle-data-receiver.yaml, tools/create-specs/src/consts.ts, tools/create-specs/src/index.ts, tools/create-specs/src/types.ts, tyk/delivery-info-services-oas.json, tyk/delivery-info-services.json, tyk/user-management-services-oas.json, tyk/vehicle-management-services-oas.json, tyk/work-planning-services-oas.json
=> Added metadata fields to all schemas

services/delivery-info-services.yaml, services/work-planning-services.yaml, specs/app.yaml, specs/full.yaml, specs/management.yaml, tools/create-specs/src/index.ts, tools/create-specs/src/types.ts, tyk/delivery-info-services-oas.json, tyk/delivery-info-services.json, tyk/work-planning-services-oas.json
=> Added tasks

services/delivery-info-services.yaml, services/user-management-services.yaml, services/vehicle-management-services.yaml, specs/app.yaml, specs/full.yaml, specs/management.yaml, tyk/delivery-info-services-oas.json, tyk/user-management-services-oas.json, tyk/vehicle-management-services-oas.json
=> Added archive to trucks, trailers, vehicles and customer sites

tools/create-specs/src/index.ts, tyk/delivery-info-services.json, tyk/user-management-services.json, tyk/vehicle-management-services.json, tyk/work-planning-services.json
=> Added options_passthrough: true to TYK definitions

services/delivery-info-services.yaml, services/user-management-services.yaml, services/vehicle-management-services.yaml, services/work-planning-services.yaml, specs/app.yaml, specs/full.yaml, specs/management.yaml, specs/vehicle-data-receiver.yaml, tools/create-specs/src/consts.ts, tools/create-specs/src/index.ts, tools/create-specs/src/types.ts, tyk/delivery-info-services-oas.json, tyk/delivery-info-services.json, tyk/user-management-services-oas.json, tyk/vehicle-management-services-oas.json, tyk/vehicle-management-services.json, tyk/work-planning-services-oas.json
- changed truck to contain activeVehicleId
- removed put request from vehicle
- opened createVehicle to driver app
Resolves #32
=> Changed route to relate to truck instead of vehicle

services/delivery-info-services.yaml, services/user-management-services.yaml, services/vehicle-management-services.yaml, services/work-planning-services.yaml, specs/app.yaml, specs/full.yaml, specs/management.yaml, tools/create-specs/src/index.ts, tools/create-specs/src/types.ts, tyk/delivery-info-services-oas.json, tyk/delivery-info-services.json, tyk/user-management-services-oas.json, tyk/vehicle-management-services-oas.json, tyk/vehicle-management-services.json, tyk/work-planning-services-oas.json
=> Added freightNumber to Freight

services/delivery-info-services.yaml, services/user-management-services.yaml, services/vehicle-management-services.yaml, services/work-planning-services.yaml, specs/app.yaml, specs/full.yaml, specs/management.yaml, tools/create-specs/src/index.ts, tools/create-specs/src/types.ts, tyk/delivery-info-services-oas.json, tyk/delivery-info-services.json, tyk/user-management-services-oas.json, tyk/vehicle-management-services-oas.json, tyk/vehicle-management-services.json, tyk/work-planning-services-oas.json
=> Added name to truck and towable

services/delivery-info-services.yaml, specs/app.yaml, specs/full.yaml, specs/management.yaml, tyk/delivery-info-services-oas.json
=> Updated freight unit schema

services/delivery-info-services.yaml, specs/app.yaml, specs/full.yaml, specs/management.yaml, tyk/delivery-info-services-oas.json
=> Added freight changes

services/delivery-info-services.yaml, specs/app.yaml, specs/full.yaml, specs/management.yaml, tyk/delivery-info-services-oas.json
=> Added task changes

services/vehicle-management-services.yaml, specs/app.yaml, specs/full.yaml, specs/management.yaml, tyk/vehicle-management-services-oas.json
=> Changed activeVehicleId to nullable field in truck

services/delivery-info-services.yaml, services/user-management-services.yaml, services/vehicle-management-services.yaml, services/work-planning-services.yaml, specs/app.yaml, specs/full.yaml, specs/management.yaml, specs/vehicle-data-receiver.yaml, tools/create-specs/src/consts.ts, tools/create-specs/src/index.ts, tools/create-specs/src/types.ts, tyk/delivery-info-services-oas.json, tyk/delivery-info-services.json, tyk/user-management-services-oas.json, tyk/user-management-services.json, tyk/vehicle-management-services-oas.json, tyk/vehicle-management-services.json, tyk/work-planning-services-oas.json, tyk/work-planning-services.json
=> Added public truck info

services/vehicle-management-services.yaml, specs/auth.yaml, specs/full.yaml, specs/vehicle-data-receiver.yaml, tyk/vehicle-management-services-oas.json, tyk/vehicle-management-services.json
=> Moved driver card endpoints under truck

services/vehicle-management-services.yaml, specs/app.yaml, specs/full.yaml, specs/vehicle-data-receiver.yaml, tyk/vehicle-management-services-oas.json
=> Added vehicle data receiver to listPublicTrucks endpoint tags

services/vehicle-management-services.yaml, specs/full.yaml, specs/management.yaml, specs/vehicle-data-receiver.yaml, tyk/vehicle-management-services-oas.json, tyk/vehicle-management-services.json
=> Added truck speed endpoints

services/vehicle-management-services.yaml, specs/full.yaml, specs/management.yaml, specs/vehicle-data-receiver.yaml, tyk/vehicle-management-services-oas.json, tyk/vehicle-management-services.json
=> Added truck location endpoints

services/user-management-services.yaml, specs/full.yaml, specs/management.yaml, tyk/user-management-services-oas.json
=> Added driverCardId filter

services/vehicle-management-services.yaml, specs/app.yaml, specs/full.yaml, specs/vehicle-data-receiver.yaml, tyk/vehicle-management-services-oas.json
https://github.com/Metatavu/vp-kuljetus-transport-management-specs/issues/78
=> added vin filter

services/vehicle-management-services.yaml, specs/app.yaml, specs/full.yaml, specs/management.yaml, specs/vehicle-data-receiver.yaml, tyk/vehicle-management-services-oas.json, tyk/vehicle-management-services.json
=> Added truck drive state endpoints

services/vehicle-management-services.yaml, specs/full.yaml, specs/vehicle-data-receiver.yaml, tyk/vehicle-management-services-oas.json, tyk/vehicle-management-services.json
=> Removed receiveTelematicData endpoint

services/work-planning-services.yaml, specs/app.yaml, tyk/work-planning-services-oas.json
=> Opened updateRoute endpoint to driver app

services/work-planning-services.yaml, specs/app.yaml, specs/full.yaml, specs/management.yaml, tyk/work-planning-services-oas.json
=> Feature 83 allow update route endpoint to driver app

services/vehicle-management-services.yaml, specs/app.yaml, specs/auth.yaml, specs/full.yaml, specs/management.yaml, specs/vehicle-data-receiver.yaml, tools/create-specs/src/index.ts, tools/create-specs/src/types.ts, tyk/vehicle-management-services-oas.json
=> Feature 87 initial support for sorting trucks listing

services/user-management-services.yaml, specs/full.yaml, specs/management.yaml, tyk/user-management-services-oas.json
=> Allow listing of drivers with api key auth

services/vehicle-management-services.yaml, specs/app.yaml, specs/auth.yaml, specs/full.yaml, tyk/vehicle-management-services-oas.json
=> Allowed driver app to list driver cards

services/user-management-services.yaml, specs/app.yaml, specs/auth.yaml, specs/full.yaml, specs/management.yaml, specs/vehicle-data-receiver.yaml, tyk/user-management-services-oas.json, tyk/user-management-services.json
=> Initial employee management

services/user-management-services.yaml, specs/app.yaml, specs/auth.yaml, specs/full.yaml, specs/management.yaml, specs/vehicle-data-receiver.yaml, tyk/user-management-services-oas.json
https://github.com/Metatavu/vp-kuljetus-transport-management-specs/issues/98
=> fix spec delete endpoint status

services/user-management-services.yaml, specs/app.yaml, specs/auth.yaml, specs/full.yaml, specs/management.yaml, specs/vehicle-data-receiver.yaml, tyk/user-management-services-oas.json, tyk/user-management-services.json
=> Initial time entry management

.gitignore, services/user-management-services.yaml, specs/app.yaml, specs/auth.yaml, specs/full.yaml, specs/management.yaml, specs/vehicle-data-receiver.yaml, tyk/user-management-services-oas.json, tyk/user-management-services.json
=> Added daily time entries

services/user-management-services.yaml, specs/app.yaml, specs/auth.yaml, specs/full.yaml, specs/management.yaml, specs/vehicle-data-receiver.yaml, tyk/user-management-services-oas.json, tyk/user-management-services.json
- Also removed WorkType entity
#102
=> Added WorkEventType enum

services/user-management-services.yaml, specs/app.yaml, specs/auth.yaml, specs/full.yaml, specs/management.yaml, specs/vehicle-data-receiver.yaml, tyk/user-management-services-oas.json, tyk/user-management-services.json
=> Initial holidays

services/user-management-services.yaml, specs/app.yaml, specs/full.yaml, specs/management.yaml, tyk/user-management-services-oas.json, tyk/user-management-services.json
=> Feature 106 refine time entry

services/user-management-services.yaml, services/vehicle-management-services.yaml, specs/app.yaml, specs/auth.yaml, specs/full.yaml, specs/management.yaml, specs/vehicle-data-receiver.yaml, tyk/user-management-services-oas.json, tyk/user-management-services.json, tyk/vehicle-management-services-oas.json
=> Feature 108 add timestamp to truckdrivercard

services/user-management-services.yaml, specs/app.yaml, specs/auth.yaml, specs/full.yaml, specs/management.yaml, specs/vehicle-data-receiver.yaml, tyk/user-management-services-oas.json, tyk/user-management-services.json
=> Feature unknown work event type

services/user-management-services.yaml, specs/app.yaml, specs/auth.yaml, specs/full.yaml, specs/management.yaml, specs/vehicle-data-receiver.yaml, tyk/user-management-services-oas.json, tyk/user-management-services.json
=> Added client apps

services/vehicle-management-services.yaml, specs/full.yaml, specs/vehicle-data-receiver.yaml, tyk/vehicle-management-services-oas.json
=> Added x-driver-card-removed-at header

services/user-management-services.yaml, specs/auth.yaml, specs/full.yaml, specs/management.yaml, tyk/user-management-services-oas.json, tyk/user-management-services.json
- also added PIN code for employee
Resolves #121
=> Added verify client app approval endpoint

services/user-management-services.yaml, specs/app.yaml, specs/full.yaml, specs/management.yaml, tyk/user-management-services-oas.json
=> Added first version of the work shift hours calculation logic

input/vehicle-management-services.yaml, services/vehicle-management-services.yaml, specs/app.yaml, specs/auth.yaml, specs/full.yaml, specs/vehicle-data-receiver.yaml, tyk/vehicle-management-services-oas.json
=> Added description for driver card management

input/user-management-services.yaml, services/user-management-services.yaml, specs/app.yaml, specs/full.yaml, specs/management.yaml, tyk/user-management-services-oas.json
=> Added SpecApp tag to listEmplyoeeWorkShifts

input/user-management-services.yaml, services/user-management-services.yaml, tyk/user-management-services-oas.json, tyk/user-management-services.json
https://github.com/Metatavu/vp-kuljetus-transport-management-specs/issues/136
=> cron task endpoint

input/user-management-services.yaml, services/user-management-services.yaml, specs/full.yaml, specs/management.yaml, tyk/user-management-services-oas.json
Removed ApiKey auth for the listDrivers endpoint, added new Role
=> Remove API key authentication for service-to-service requests 

input/user-management-services.yaml, services/user-management-services.yaml, specs/app.yaml, specs/full.yaml, specs/management.yaml, tyk/user-management-services-oas.json
https://github.com/Metatavu/vp-kuljetus-transport-management-specs/issues/141
=> added 2 new filters for work shifts

input/vehicle-management-services.yaml, services/vehicle-management-services.yaml, specs/full.yaml, specs/management.yaml, specs/vehicle-data-receiver.yaml, tyk/vehicle-management-services-oas.json, tyk/vehicle-management-services.json
=> Added support for TruckOdometerReadings

input/user-management-services.yaml, services/user-management-services.yaml, specs/app.yaml, specs/full.yaml, specs/management.yaml, tyk/user-management-services-oas.json, tyk/user-management-services.json
=> Added payroll exports

input/vehicle-management-services.yaml, services/vehicle-management-services.yaml, specs/app.yaml, specs/full.yaml, specs/management.yaml, specs/vehicle-data-receiver.yaml, tyk/vehicle-management-services-oas.json, tyk/vehicle-management-services.json
=> Bug 146 change temperature reading timestamp to unix timestamp

input/vehicle-management-services.yaml, services/vehicle-management-services.yaml, specs/full.yaml, specs/vehicle-data-receiver.yaml, tyk/vehicle-management-services-oas.json
- Added sourceType field
- Described potential error values from truck/towable
Resolves #148
=> Changed TemperatureReading macAddress to hardwareSensorId

input/vehicle-management-services.yaml, services/vehicle-management-services.yaml, specs/full.yaml, specs/management.yaml, tyk/vehicle-management-services-oas.json
=> Feature 150 temperature to timestamp

input/vehicle-management-services.yaml, services/vehicle-management-services.yaml, specs/full.yaml, specs/management.yaml, tyk/vehicle-management-services-oas.json
=> Fixed tags in thermometers

input/user-management-services.yaml, services/user-management-services.yaml, specs/app.yaml, specs/full.yaml, specs/management.yaml, tyk/user-management-services-oas.json
=> Added work types

input/delivery-info-services.yaml, services/delivery-info-services.yaml, tyk/delivery-info-services-oas.json
=> API key parameter name fix

input/delivery-info-services.yaml, services/delivery-info-services.yaml, specs/full.yaml, specs/management.yaml, specs/terminal-device.yaml, specs/vehicle-data-receiver.yaml, tyk/delivery-info-services-oas.json
=> Device identifier parameter name

input/user-management-services.yaml, services/user-management-services.yaml, specs/app.yaml, specs/full.yaml, specs/management.yaml, tyk/user-management-services-oas.json
=> Changed datetimes to date

input/delivery-info-services.yaml, input/vehicle-management-services.yaml, services/delivery-info-services.yaml, services/vehicle-management-services.yaml, specs/full.yaml, specs/management.yaml, specs/terminal-device.yaml, specs/vehicle-data-receiver.yaml, tyk/delivery-info-services-oas.json, tyk/vehicle-management-services-oas.json
=> Changed operation IDs

input/user-management-services.yaml, services/user-management-services.yaml, specs/app.yaml, specs/full.yaml, specs/management.yaml, tyk/user-management-services-oas.json
=> Added a field for default truck id

input/user-management-services.yaml, services/user-management-services.yaml, specs/app.yaml, specs/full.yaml, specs/management.yaml, tyk/user-management-services-oas.json
=> Renamded truckIds to truckIdsFromEvents

input/user-management-services.yaml, input/vehicle-management-services.yaml, services/user-management-services.yaml, services/vehicle-management-services.yaml, specs/app.yaml, specs/full.yaml, specs/management.yaml, tyk/user-management-services-oas.json, tyk/vehicle-management-services-oas.json
=> Feature 179 cost center

input/user-management-services.yaml, services/user-management-services.yaml, specs/app.yaml, specs/full.yaml, specs/management.yaml, tyk/user-management-services-oas.json
=> Removed default truck id

input/user-management-services.yaml, services/user-management-services.yaml, specs/app.yaml, specs/full.yaml, specs/management.yaml, tyk/user-management-services-oas.json
=> Cost centers from events
